service: openai-quickstart-node

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  timeout: 10

functions:
  app:
    handler: node_modules/next-serverless/lib/server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      NODE_ENV: production
